# Generated by Django 3.2 on 2021-05-29 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admission_title', models.CharField(max_length=200)),
                ('unique_advt_number_primary_key', models.TextField(unique=True)),
                ('fee_desc', models.TextField(blank=True, null=True)),
                ('important_dates', models.TextField(blank=True, null=True)),
                ('admission_detail_desc', models.TextField(blank=True, null=True)),
                ('post_important_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_provider', models.CharField(max_length=200)),
                ('document_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_fee', models.TextField(blank=True, null=True)),
                ('unique_advt_number_primary_key', models.TextField(unique=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('document_detail_desc', models.TextField(blank=True, null=True)),
                ('document_important_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Important',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=200)),
                ('name_of_scheme', models.CharField(blank=True, max_length=200, null=True)),
                ('fee_detail', models.TextField(blank=True, null=True)),
                ('primary_key_name', models.TextField(unique=True)),
                ('requirement_desc', models.TextField(blank=True, null=True)),
                ('scheme_detail_desc', models.TextField(blank=True, null=True)),
                ('scheme_important_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_provider_name', models.CharField(blank=True, max_length=100, null=True)),
                ('post_title', models.CharField(max_length=200)),
                ('total_post', models.IntegerField(default='0', null=True)),
                ('advt_number', models.TextField(blank=True, null=True)),
                ('fee_desc', models.TextField(blank=True, null=True)),
                ('post_dates', models.TextField(blank=True, null=True)),
                ('post_last_date', models.DateField()),
                ('age_desc', models.TextField(blank=True, null=True)),
                ('post_detail_desc', models.TextField(blank=True, null=True)),
                ('post_important_link', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.post_category')),
                ('post_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.post_stage')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_app.post_info')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='post_app.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
